resource configservice_bit_config_field creative_cloud_connector_use_asset_preview_thumbnail {
    default_value = false
    product_id = resource.configservice_product.media_manager_5.id
    group = 'Creative Cloud Connector'
    key = 'creativeCloudConnectorUseAssetPreviewThumbnail'
    title = 'Use DAM-generated thumbnails'
    description = 'When enabled, the Cache and Link Manager will use thumbnails generated by the DAM system, rather than utilizing locally generated thumbnails.'
    hidden = true
}